# Docs: https://circleci.com/docs/2.0/sample-config/
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-node

    working_directory: ~/laminar

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx2000m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          name: Restore Sbt Dependencies Cache
          keys:
            - sbt-deps--{{ checksum "build.sbt" }}

      # Make sure this exists, or checksum will fail (we might want to commit yarn.lock...)
      - run: touch yarn.lock

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages--{{ checksum "yarn.lock" }}

      - run: cat /dev/null | sbt +test:compile

      - save_cache:
          name: Save Sbt Dependencies Cache
          paths:
            - ~/.m2
            - ~/.ivy2/cache
            - ~/.sbt
          key: sbt-deps--{{ checksum "build.sbt" }}
      - save_cache:
          name: Save Yarn Package Cache
          paths:
            - ~/.cache/yarn
          key: yarn-packages--{{ checksum "yarn.lock" }}


      # run tests!
      - run: cat /dev/null | sbt +test:test

workflows:
  run_build:
    jobs:
      - build
          filters:
            branches:
